eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    fetch-registry: false
    
  
spring:  application:    name: EurekaServer
    
    
server:  port: 8761
    